name: exploreapp
description: The application of Explorea.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0-alpha.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.0.7 # https://flutter.dev/docs/cookbook/persistence/key-value

  flutter_map: any

  carousel_slider: ^4.0.0

  video_player: ^2.2.15 # https://docs.flutter.dev/cookbook/plugins/play-video

  fluttertoast: 8.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # For Firebase
  # check version on : https://firebase.flutter.dev/
  cloud_firestore: ^2.5.3
  firebase_auth: ^3.1.1
  provider: ^6.0.0
  firebase_core: ^1.10.0
  geolocator: ^8.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.9.2" # flutter pub run flutter_launcher_icons:main

  # Helps rename Android package name :
  change_app_package_name: ^1.0.0 # flutter pub run change_app_package_name:main com.new.package.name

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/explorea-logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/adventure_1_gulls/
    - assets/adventure_1_gulls/items/
    - assets/adventure_1_gulls/sounds/
    - assets/icon/
    - assets/adventure-background-pict/
    - assets/home-scenes/

  fonts:
    - family: ABCProphet
      fonts:
        - asset: assets/fonts/ABCProphet/ABCProphet-Regular.ttf
        - asset: assets/fonts/ABCProphet/ABCProphet-RegularItalic.ttf
          style: italic

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
